// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbvuyfoezwmcoyqxjicv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFidnV5Zm9lendtY295cXhqaWN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3Mzc0MDMsImV4cCI6MjA2MDMxMzQwM30.AyHWbkGe8hk28Yorxx_WiEb5jTqrbSHcZUyEWsXGfcw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);